### ISSUE TITLE
Build failure under Windows 10

### ISSUE THREAD

**Issue by sanmai-NL** [malept/crypto-hash#10]
crypto-hash v. 0.3.1. fails to build for me. I used Windows 10 Enterprise build 17763.rs5_release.180914-1434. You can download a VM with this environment at https://developer.microsoft.com/en-us/windows/downloads/virtual-machines .

rustc output:
```
thread 'main' panicked at 'failed unsafe {
    CryptAcquireContextW(&mut hcp, ptr::null(), ptr::null(), PROV_RSA_AES,
                         CRYPT_VERIFYCONTEXT | CRYPT_SILENT)
}: Provider DLL failed to initialize correctly. (os error -2146893795)', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\crypto-hash-0.3.1\src\imp\cryptoapi.rs:91:9
```

**Comment by malept** [comment]
* Does it fail to build, or cause a panic at runtime?
* What version of Rust are you compiling with?
* v0.3.1 is not the latest version of `crypto-hash`. Can you please try the latest version?
* Is this only with Windows 10 Enterprise? What about other versions of Windows 10?
* Can you please provide detailed steps to reproduce your error, and a more detailed console output?

**Comment by sanmai-NL** [comment]
* The panic is reported from custom build tooling, it seems to originate from a `cargo` invocation.
* A recent nightly. More details later, if you need them.
* v0.3.1. is a dependency, I can't switch it out easily.
* I do not know.
* There is no more relevant output. I will try to build a reproduction then.

**Comment by sanmai-NL** [comment]
The reverse dependency is on [Cargo](https://github.com/rust-lang/cargo/blob/2510c0cd7bfc902dd318d1cce60ed46bf6ff4ece/Cargo.toml#L26). The Cargo binary fails to use crypto-hash. I cannot upgrade the version easily then.

**Comment by sanmai-NL** [comment]
I solved it. The problem was that Cargo was invoked with a clear environment. This works fine under other OSes, but not under Windows. This is a bug in the standard library (rust-lang/rust#31259).
