### ISSUE TITLE
How to unhash

### ISSUE THREAD

**Issue by hasanAjsf** [malept/crypto-hash#8]
Assuming I used your sample code:
```rust
use crypto_hash::{Algorithm, hex_digest};

let digest = hex_digest(Algorithm::SHA256, b"crypto-hash");
println!("{}", digest);
```
The output will be:
```bash
fd1afb6022cd4d47c890961c533928eacfe8219f1b2524f7fb2a61847ddf8c27
```

Then, how ca I `unhash` it, if I want to read the original input

**Comment by malept** [comment]
The hashes in the `Algorithm` enum are all [cryptographic hashes](https://en.wikipedia.org/wiki/Cryptographic_hash_function). By definition, it's extremely difficult to "unhash". Hashing is not meant for encryption, you'd want a different library for that.
